apiVersion: apps/v1
kind: Deployment
metadata:
  name: housing_api
  namespace: deployment
  labels:
    app: housing_api

spec:
  replicas: 2
  selector:
    matchLabels:
      app: housing_api
  template:
    metadata:
      labels:
        app: housing_api

    spec:
      containers:
        - name: housing_api
          image: lukhee/housing_api:latest
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: housing_api
  namespace: deployment
spec:
  selector:
    app: housing_api
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
