apiVersion: apps/v1
kind: Deployment
metadata:
  name: housing
  namespace: deployment
  labels:
    app: housing

spec:
  replicas: 2
  selector:
    matchLabels:
      app: housing
  template:
    metadata:
      labels:
        app: housing

    spec:
      containers:
        - name: housing
          image: lukhee/housing_api:latest
          env:
          - name: VERSION
            value: 1.0.0
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: housing
  namespace: deployment
spec:
  selector:
    app: housing
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
