apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: housing-ingress
  namespace: deployment
  annotations:
    kubernetes.io/ingree.class: ngnix
spec:
  ingressClassName: nginx
  rules:
  - host: house.devlook.tech
    http:
      paths:
      - path: "/grafana"
        pathType: Prefix
        backend:
          service:
            name: prometheus-grafana  
            port:
              number: 80
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: housing 
            port:
              number: 80